#include "arduino_secrets.h"
/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled 2"
  https://create.arduino.cc/cloud/things/aa16e64a-0b28-4494-a02b-40f16ad64979 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  String msg;
  bool motion;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
#include <Servo.h>

Servo myservo; 

void setup() {
  pinMode(15,INPUT);
  Serial.begin(9600);
  // pinMode(17,OUTPUT);
  myservo.attach(17);
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  bool sensor;
  sensor=digitalRead(15);
  if(sensor==LOW){
    Serial.print("No motion in sight.\n\n");
    msg="No Motion Detected.";
    motion=sensor;
    digitalWrite(17,LOW);
    delay(500);
  
  }
  else
  {
    Serial.print("Motion Detected\n\n");
    msg="Motion Detected.";
    motion=sensor;
    digitalWrite(17,HIGH);
    delay(500);
    for (int pos = 0; pos <= 180; pos += 1) { // goes from 0 degrees to 180 degrees
    // in steps of 1 degree
    myservo.write(pos);              // tell servo to go to position in variable 'pos'
    delay(15);                       // waits 15ms for the servo to reach the position
  }
    for (int pos = 180; pos >= 0; pos -= 1) { // goes from 0 degrees to 180 degrees
    // in steps of 1 degree
    myservo.write(pos);              // tell servo to go to position in variable 'pos'
    delay(15);                       // waits 15ms for the servo to reach the position
  }
  
  }
  
  
}


/*
  Since Motion is READ_WRITE variable, onMotionChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onMotionChange()  {
  // Add your code here to act upon Motion change
}

/*
  Since Msg is READ_WRITE variable, onMsgChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onMsgChange()  {
  // Add your code here to act upon Msg change
}